---
output: 
  word_document:
    reference_docx: ../../prf/PFA_template.dotx
---

```{r setup, include=FALSE}

require("knitr")
knitr::opts_chunk$set(echo = FALSE,	message = FALSE,	warning = FALSE,	crop = TRUE,	comment = "")
knit_hooks$set(crop = hook_pdfcrop)
```


```{r initialization, include=FALSE}
# ===========================================================================
# map of FAO areas.Rmd
# Martin Pastoors

# 29/01/2017 for Sean and Gerard
# 30/03/2017 Update for Gerard
# 04/04/2017 Irish closure added
# 27/04/2017 NAFO area added
# 24/08/2017 Update code for changes in R
# 19/12/2017 Cleaned up and documented the code
# 22/12/2017 Converted to RMarkdown to generate documents for skippers
# ===========================================================================

library(tidyverse)
library(stringr)
library(mapproj)

#  load the map files
load("../../prf/rdata/world.df.RData")
load("../../prf/rdata/eez.df.RData")
load("../../prf/rdata/fao.df.RData")
load("../../prf/rdata/highsea.df.RData")
load("../../prf/rdata/uklimit.df.RData")
load("../../prf/rdata/icesrectangles.df.RData")

# Source all the utiles
source("my_utils.r")

# calculate area midpoints
fao_midpoints <-
  fao.df %>% 
  group_by(id, F_CODE) %>% 
  summarize(long = mean(range(long), na.rm=TRUE),
            lat  = mean(range(lat), na.rm=TRUE)) 

eez_midpoints <-
  eez.df %>% 
  group_by(id, ISO_Ter1) %>% 
  summarize(long = mean(range(long), na.rm=TRUE),
            lat  = mean(range(lat), na.rm=TRUE)) %>% 
  arrange(ISO_Ter1)

ices_midpoints <-
  icesrectangles.df %>% 
  group_by(id, rect) %>% 
  summarize(long = mean(range(long), na.rm=TRUE),
            lat  = mean(range(lat), na.rm=TRUE)) %>% 
  arrange(rect)


area34   <- c("34.1.11","34.1.12","34.1.13",
              "34.1.31","34.1.32",
              "34.3.11","34.3.12","34.3.13",
              "34.1.2",
              "34.2",
              "34.3.2")

area27   <- c("27.2.a",
              "27.3.a",
              "27.4", 
              "27.5.a",
              "27.5.b",
              "27.6.b", "27.6.a",
              "27.7.a","27.7.b","27.7.c","27.7.d","27.7.e","27.7.f", "27.7.g","27.7.h",
              "27.7.j", "27.7.k",
              "27.8.a","27.8.b","27.8.c", "27.8.d", "27.8.e") 

area27north<- c("27.2.a",
              "27.3.a",
              "27.4.a","27.4.b","27.4.c", 
              "27.5.a.1", "27.5.a.2",
              "27.5.b.1.a","27.5.b.1.b", "27.5.b.2",
              "27.6.b.1", "27.6.b.2","27.6.a" ) 

area27south<- c("27.7.a","27.7.b","27.7.c.2","27.7.d","27.7.e","27.7.f", "27.7.g","27.7.h",
              "27.7.c.1", "27.7.j.1", "27.7.k.1",
              "27.7.c.2", "27.7.j.2", "27.7.k.2",
              "27.8.a","27.8.b","27.8.c",
              "27.8.d.1", "27.8.e.1",
              "27.8.d.2", "27.8.e.2",
              "27.10.b",
              "27.12.a.1","27.12.a.2", "27.12.a.3","27.12.a.4",
              "27.12.b","27.12.c","27.12.d") 

area27channel <- c("27.4.c", 
              "27.7.d","27.7.e","27.7.f", "27.7.g","27.7.h")
  

area27west <- c("27.4.a", 
              "27.6.a","27.6.b","27.7.b", "27.7.c", "27.5.b")

```

# PFA area maps: ICES rectangles, FAO area and economic zones

&nbsp;  

Martin Pastoors, `r format(Sys.time(), '%d/%m/%Y')`

&nbsp;  

## FAO area 27 Northeastern Atlantic

### Whole area (in subareas)

```{r, echo=FALSE, fig.width=10, fig.asp=1.25, fig.align="center", message=FALSE, warning=FALSE}

# different options for specific areas to be shown
myareas   <- c("27.2.a",
              "27.3.a",
              "27.4", 
              "27.5.b","27.6","27.7","27.8")

# set limits based on selected areas
mylimits <- 
  filter(fao.df, F_CODE %in% myareas) %>% 
  summarise(xmin = floor(min(long, na.rm=TRUE)),
            # xmax = ceiling(max(long, na.rm=TRUE)),
            xmax = 22, 
            ymin = floor(min(lat, na.rm=TRUE)),
            ymax = ceiling(max(lat, na.rm=TRUE)) )

# set area names for selected areas
mynames <-
  filter(fao.df, F_CODE %in% myareas) %>% 
  group_by(F_CODE) %>% 
  filter(row_number() == 1) %>% 
  select(F_CODE) %>% 
  left_join(fao_midpoints, by=c("F_CODE"))

# write.csv(fao.df, file="excel/fao.csv")
# sort(unique(fao.df$F_CODE))

fao.df %>%
  filter(F_CODE  %in% myareas) %>% 
  filter(hole == FALSE) %>% 
  # write.csv(., file="excel/fao.csv")
  
  ggplot() + 
  theme_publication() +
  theme(
    panel.grid.major   = element_line(colour="gray"),
    panel.grid.minor.y = element_line(colour="gray", linetype="dashed"),
    panel.spacing      = unit(c(0,0,0,0), "lines"),
    strip.background   = element_rect(colour=NA, fill = "#f0f0f0"),
    panel.border       = element_rect(colour="black" , size=0.2),
    legend.position    = "none") +
  
  labs(x = NULL, y = NULL) +    
  coord_quickmap(xlim=c(mylimits$xmin,mylimits$xmax) , ylim=c(mylimits$ymin,mylimits$ymax)) +

  geom_polygon(               aes(long, lat, group=group, fill=factor(F_SUBAREA)),
                              size=0.1, colour="black", alpha=0.7) +
  geom_polygon(data=world.df, aes(long, lat, group=group), 
                              fill="cornsilk", size=0.1, colour="gray60") +
  geom_polygon(data=eez.df,   aes(long, lat, group=group), 
                              fill=NA, size=0.5, colour="gray40", alpha=0.7, lty="dashed") +
  geom_text(data=mynames, aes(long, lat, label = F_CODE), size=4, fontface="bold") +
  
  scale_y_continuous(breaks = seq(mylimits$ymin, mylimits$ymax, 1),
                     labels = seq(mylimits$ymin, mylimits$ymax, 1) ) +
  scale_x_continuous(breaks = seq(mylimits$xmin, mylimits$xmax, 1) ) 

```

##### page break

```{r, echo=FALSE, fig.width=10, fig.asp=1.25, fig.align="center", message=FALSE, warning=FALSE}

# different options for specific areas to be shown
myareas   <- c("27.2.a",
              "27.3.a",
              "27.4", 
              "27.5.b","27.6","27.7","27.8")

# set limits based on selected areas
mylimits <- 
  filter(fao.df, F_CODE %in% myareas) %>% 
  summarise(xmin = floor(min(long, na.rm=TRUE)),
            # xmax = ceiling(max(long, na.rm=TRUE)),
            xmax = 22, 
            ymin = floor(min(lat, na.rm=TRUE)),
            ymax = ceiling(max(lat, na.rm=TRUE)) )

# set area names for selected areas
mynames <-
  eez_midpoints 

# write.csv(fao.df, file="excel/fao.csv")
# sort(unique(fao.df$F_CODE))

fao.df %>%
  filter(F_CODE  %in% myareas) %>% 
  filter(hole == FALSE) %>% 
  # write.csv(., file="excel/fao.csv")
  
  ggplot() + 
  theme_publication() +
  theme(
    panel.grid.major   = element_line(colour="gray"),
    panel.grid.minor.y = element_line(colour="gray", linetype="dashed"),
    panel.spacing      = unit(c(0,0,0,0), "lines"),
    strip.background   = element_rect(colour=NA, fill = "#f0f0f0"),
    panel.border       = element_rect(colour="black" , size=0.2),
    legend.position    = "none") +
  
  labs(x = NULL, y = NULL) +    
  coord_quickmap(xlim=c(mylimits$xmin,mylimits$xmax) , ylim=c(mylimits$ymin,mylimits$ymax)) +

  geom_polygon(               aes(long, lat, group=group),
                              fill=NA, size=0.1, colour="black", alpha=0.3) +
  geom_polygon(data=eez.df,   aes(long, lat, group=group, fill=(ISO_Ter1)), 
                              size=0.5, colour="gray40", alpha=0.7, lty="dashed") +
  geom_polygon(data=world.df, aes(long, lat, group=group), 
                              fill="cornsilk", size=0.1, colour="gray60") +
  geom_text(data=mynames, aes(long, lat, label = ISO_Ter1), size=4, fontface="bold") +
  
  scale_y_continuous(breaks = seq(mylimits$ymin, mylimits$ymax, 1),
                     labels = seq(mylimits$ymin, mylimits$ymax, 1) ) +
  scale_x_continuous(breaks = seq(mylimits$xmin, mylimits$xmax, 1) ) 

```

##### Page break 

### Western area

```{r, echo=FALSE, fig.width=10, fig.asp=0.7, fig.align="center", message=FALSE, warning=FALSE}

# different options for specific areas to be shown
myareas   <- area27west

# set limits based on selected areas
mylimits <- 
  filter(fao.df, F_CODE %in% myareas) %>% 
  summarise(xmin = floor(min(long, na.rm=TRUE)),
            xmax = ceiling(max(long, na.rm=TRUE)),
            ymin = floor(min(lat, na.rm=TRUE)),
            ymax = ceiling(max(lat, na.rm=TRUE)) )

# set area names for selected areas
mynames <-
  filter(fao.df, F_CODE %in% myareas) %>% 
  group_by(F_CODE) %>% 
  filter(row_number() == 1) %>% 
  select(F_CODE) %>% 
  left_join(fao_midpoints, by=c("F_CODE"))

# write.csv(fao.df, file="excel/fao.csv")
# sort(unique(fao.df$F_CODE))

fao.df %>%
  filter(F_CODE  %in% myareas) %>% 
  filter(hole == FALSE) %>% 
  # write.csv(., file="excel/fao.csv")
  
  ggplot() + 
  theme_publication() +
  theme(
    panel.grid.major   = element_line(colour="gray"),
    panel.grid.minor.y = element_line(colour="gray", linetype="dashed"),
    panel.spacing      = unit(c(0,0,0,0), "lines"),
    strip.background   = element_rect(colour=NA, fill = "#f0f0f0"),
    panel.border       = element_rect(colour="black" , size=0.2),
    legend.position    = "none") +
  
  labs(x = NULL, y = NULL) +    
  coord_quickmap(xlim=c(mylimits$xmin,mylimits$xmax) , ylim=c(mylimits$ymin,mylimits$ymax)) +

  geom_polygon(               aes(long, lat, group=group, fill=factor(F_DIVISION)),
                              size=0.1, colour="black", alpha=0.7) +
  geom_polygon(data=world.df, aes(long, lat, group=group), 
                              fill="cornsilk", size=0.1, colour="gray60") +
  geom_polygon(data=eez.df,   aes(long, lat, group=group), 
                              fill=NA, size=0.5, colour="gray40", alpha=0.7, lty="dashed") +
  geom_text(data=mynames, aes(long, lat, label = F_CODE), size=4, fontface="bold") +
  
  scale_y_continuous(breaks = seq(mylimits$ymin, mylimits$ymax, 1),
                     labels = seq(mylimits$ymin, mylimits$ymax, 1) ) +
  scale_x_continuous(breaks = seq(mylimits$xmin, mylimits$xmax, 1) ) 

```

```{r, echo=FALSE, fig.width=10, fig.asp=0.7, fig.align="center", message=FALSE, warning=FALSE}

# different options for specific areas to be shown
# myareas   <- area27west
myareas   <- c("27.6.a")

# set limits based on selected areas
mylimits <- 
  filter(fao.df, F_CODE %in% myareas) %>% 
  summarise(xmin = floor(min(long, na.rm=TRUE)),
            xmax = ceiling(max(long, na.rm=TRUE)),
            ymin = floor(min(lat, na.rm=TRUE)),
            ymax = ceiling(max(lat, na.rm=TRUE)) )

# plot
fao.df %>%
  filter(F_CODE  %in% myareas) %>% 
  filter(hole == FALSE) %>% 

  ggplot() + 
  theme_publication() +
  theme(
    panel.grid.major   = element_line(colour="gray"),
    panel.grid.minor.y = element_line(colour="gray", linetype="dashed"),
    panel.spacing      = unit(c(0,0,0,0), "lines"),
    strip.background   = element_rect(colour=NA, fill = "#f0f0f0"),
    panel.border       = element_rect(colour="black" , size=0.2),
    legend.position    = "none") +
  
  labs(x = NULL, y = NULL) +    
  coord_quickmap(xlim=c(mylimits$xmin,mylimits$xmax) , ylim=c(mylimits$ymin,mylimits$ymax)) +

  geom_polygon(               aes(long, lat, group=group, fill=factor(F_DIVISION)),
                              size=0.1, colour="gray40", alpha=0.7) +
  geom_polygon(data=eez.df,   aes(long, lat, group=group), 
                              fill=NA, size=0.5, colour="gray40", alpha=0.7, lty="dashed") +
  geom_polygon(data=icesrectangles.df, aes(long, lat, group=group),
                              fill=NA, colour="black") +
  geom_text(data=ices_midpoints, aes(long, lat, label = rect), size=4, fontface="bold") +
  geom_polygon(data=world.df, aes(long, lat, group=group), 
                              fill="cornsilk", size=0.1, colour="gray60", alpha=0.95) +
  
  scale_y_continuous(breaks = seq(mylimits$ymin, mylimits$ymax, 1),
                     labels = seq(mylimits$ymin, mylimits$ymax, 1) ) +
  scale_x_continuous(breaks = seq(mylimits$xmin, mylimits$xmax, 1) ) 

```


```{r, echo=FALSE, fig.width=10, fig.asp=0.7, fig.align="center", message=FALSE, warning=FALSE}

# different options for specific areas to be shown
myareas   <- area27west

# set limits based on selected areas
mylimits <- 
  filter(fao.df, F_CODE %in% myareas) %>% 
  summarise(xmin = floor(min(long, na.rm=TRUE)),
            xmax = ceiling(max(long, na.rm=TRUE)),
            ymin = floor(min(lat, na.rm=TRUE)),
            ymax = ceiling(max(lat, na.rm=TRUE)) )

# set area names for selected areas
mynames <-
  eez_midpoints %>% 
  bind_rows(data.frame(ISO_Ter1="DEU", lat = 54, long = 7.5),
            data.frame(ISO_Ter1="GBR", lat = 53.4, long = 1.5 ),
            data.frame(ISO_Ter1="FRA", lat = 49.5, long = -1.0 ),
            data.frame(ISO_Ter1="IRE", lat = 51.2, long = -8.0 )
            )

# plot
fao.df %>%
  filter(F_CODE  %in% myareas) %>% 
  filter(hole == FALSE) %>% 
  # write.csv(., file="excel/fao.csv")
  
  ggplot() + 
  theme_publication() +
  theme(
    panel.grid.major   = element_line(colour="gray"),
    panel.grid.minor.y = element_line(colour="gray", linetype="dashed"),
    panel.spacing      = unit(c(0,0,0,0), "lines"),
    strip.background   = element_rect(colour=NA, fill = "#f0f0f0"),
    panel.border       = element_rect(colour="black" , size=0.2),
    legend.position    = "none") +
  
  labs(x = NULL, y = NULL) +    
  coord_quickmap(xlim=c(mylimits$xmin,mylimits$xmax) , ylim=c(mylimits$ymin,mylimits$ymax)) +

  geom_polygon(               aes(long, lat, group=group),
                              fill=NA, size=0.1, colour="black", alpha=0.3) +
  geom_polygon(data=eez.df,   aes(long, lat, group=group, fill=(ISO_Ter1)), 
                              size=0.5, colour="gray40", alpha=0.7, lty="dashed") +
  geom_polygon(data=world.df, aes(long, lat, group=group), 
                              fill="cornsilk", size=0.1, colour="gray60") +
  geom_text(data=mynames, aes(long, lat, label = ISO_Ter1), size=4, fontface="bold") +
  
  scale_y_continuous(breaks = seq(mylimits$ymin, mylimits$ymax, 1),
                     labels = seq(mylimits$ymin, mylimits$ymax, 1) ) +
  scale_x_continuous(breaks = seq(mylimits$xmin, mylimits$xmax, 1) ) 

```

### Channel area 

```{r, echo=FALSE, fig.width=10, fig.asp=0.7, fig.align="center", message=FALSE, warning=FALSE}

# different options for specific areas to be shown
myareas   <- area27channel

# set limits based on selected areas
mylimits <- 
  filter(fao.df, F_CODE %in% myareas) %>% 
  summarise(xmin = floor(min(long, na.rm=TRUE)),
            xmax = ceiling(max(long, na.rm=TRUE)),
            ymin = floor(min(lat, na.rm=TRUE)),
            ymax = ceiling(max(lat, na.rm=TRUE)) )

# set area names for selected areas
mynames <-
  filter(fao.df, F_CODE %in% myareas) %>% 
  group_by(F_CODE) %>% 
  filter(row_number() == 1) %>% 
  select(F_CODE) %>% 
  left_join(fao_midpoints, by=c("F_CODE"))

# write.csv(fao.df, file="excel/fao.csv")
# sort(unique(fao.df$F_CODE))

fao.df %>%
  filter(F_CODE  %in% myareas) %>% 
  filter(hole == FALSE) %>% 
  # write.csv(., file="excel/fao.csv")
  
  ggplot() + 
  theme_publication() +
  theme(
    panel.grid.major   = element_line(colour="gray"),
    panel.grid.minor.y = element_line(colour="gray", linetype="dashed"),
    panel.spacing      = unit(c(0,0,0,0), "lines"),
    strip.background   = element_rect(colour=NA, fill = "#f0f0f0"),
    panel.border       = element_rect(colour="black" , size=0.2),
    legend.position    = "none") +
  
  labs(x = NULL, y = NULL) +    
  coord_quickmap(xlim=c(mylimits$xmin,mylimits$xmax) , ylim=c(mylimits$ymin,mylimits$ymax)) +

  geom_polygon(               aes(long, lat, group=group, fill=factor(F_DIVISION)),
                              size=0.1, colour="black", alpha=0.7) +
  geom_polygon(data=world.df, aes(long, lat, group=group), 
                              fill="cornsilk", size=0.1, colour="gray60") +
  geom_polygon(data=eez.df,   aes(long, lat, group=group), 
                              fill=NA, size=0.5, colour="gray40", alpha=0.7, lty="dashed") +
  geom_text(data=mynames, aes(long, lat, label = F_CODE), size=4, fontface="bold") +
  
  scale_y_continuous(breaks = seq(mylimits$ymin, mylimits$ymax, 1),
                     labels = seq(mylimits$ymin, mylimits$ymax, 1) ) +
  scale_x_continuous(breaks = seq(mylimits$xmin, mylimits$xmax, 1) ) 

```

```{r, echo=FALSE, fig.width=10, fig.asp=0.7, fig.align="center", message=FALSE, warning=FALSE}

# different options for specific areas to be shown
myareas   <- area27channel

# set limits based on selected areas
mylimits <- 
  filter(fao.df, F_CODE %in% myareas) %>% 
  summarise(xmin = floor(min(long, na.rm=TRUE)),
            xmax = ceiling(max(long, na.rm=TRUE)),
            ymin = floor(min(lat, na.rm=TRUE)),
            ymax = ceiling(max(lat, na.rm=TRUE)) )

# plot
fao.df %>%
  filter(F_CODE  %in% myareas) %>% 
  filter(hole == FALSE) %>% 

  ggplot() + 
  theme_publication() +
  theme(
    panel.grid.major   = element_line(colour="gray"),
    panel.grid.minor.y = element_line(colour="gray", linetype="dashed"),
    panel.spacing      = unit(c(0,0,0,0), "lines"),
    strip.background   = element_rect(colour=NA, fill = "#f0f0f0"),
    panel.border       = element_rect(colour="black" , size=0.2),
    legend.position    = "none") +
  
  labs(x = NULL, y = NULL) +    
  coord_quickmap(xlim=c(mylimits$xmin,mylimits$xmax) , ylim=c(mylimits$ymin,mylimits$ymax)) +

  geom_polygon(               aes(long, lat, group=group, fill=factor(F_DIVISION)),
                              size=0.1, colour="gray40", alpha=0.7) +
  geom_polygon(data=eez.df,   aes(long, lat, group=group), 
                              fill=NA, size=0.5, colour="gray40", alpha=0.7, lty="dashed") +
  geom_polygon(data=icesrectangles.df, aes(long, lat, group=group),
                              fill=NA, colour="black") +
  geom_text(data=ices_midpoints, aes(long, lat, label = rect), size=4, fontface="bold") +
  geom_polygon(data=world.df, aes(long, lat, group=group), 
                              fill="cornsilk", size=0.1, colour="gray60", alpha=0.95) +
  
  scale_y_continuous(breaks = seq(mylimits$ymin, mylimits$ymax, 1),
                     labels = seq(mylimits$ymin, mylimits$ymax, 1) ) +
  scale_x_continuous(breaks = seq(mylimits$xmin, mylimits$xmax, 1) ) 

```


```{r, echo=FALSE, fig.width=10, fig.asp=0.7, fig.align="center", message=FALSE, warning=FALSE}

# different options for specific areas to be shown
myareas   <- area27channel

# set limits based on selected areas
mylimits <- 
  filter(fao.df, F_CODE %in% myareas) %>% 
  summarise(xmin = floor(min(long, na.rm=TRUE)),
            xmax = ceiling(max(long, na.rm=TRUE)),
            ymin = floor(min(lat, na.rm=TRUE)),
            ymax = ceiling(max(lat, na.rm=TRUE)) )

# set area names for selected areas
mynames <-
  eez_midpoints %>% 
  bind_rows(data.frame(ISO_Ter1="DEU", lat = 54, long = 7.5),
            data.frame(ISO_Ter1="GBR", lat = 53.4, long = 1.5 ),
            data.frame(ISO_Ter1="FRA", lat = 49.5, long = -1.0 ),
            data.frame(ISO_Ter1="IRE", lat = 51.2, long = -8.0 )
            )

# plot
fao.df %>%
  filter(F_CODE  %in% myareas) %>% 
  filter(hole == FALSE) %>% 
  # write.csv(., file="excel/fao.csv")
  
  ggplot() + 
  theme_publication() +
  theme(
    panel.grid.major   = element_line(colour="gray"),
    panel.grid.minor.y = element_line(colour="gray", linetype="dashed"),
    panel.spacing      = unit(c(0,0,0,0), "lines"),
    strip.background   = element_rect(colour=NA, fill = "#f0f0f0"),
    panel.border       = element_rect(colour="black" , size=0.2),
    legend.position    = "none") +
  
  labs(x = NULL, y = NULL) +    
  coord_quickmap(xlim=c(mylimits$xmin,mylimits$xmax) , ylim=c(mylimits$ymin,mylimits$ymax)) +

  geom_polygon(               aes(long, lat, group=group),
                              fill=NA, size=0.1, colour="black", alpha=0.3) +
  geom_polygon(data=eez.df,   aes(long, lat, group=group, fill=(ISO_Ter1)), 
                              size=0.5, colour="gray40", alpha=0.7, lty="dashed") +
  geom_polygon(data=world.df, aes(long, lat, group=group), 
                              fill="cornsilk", size=0.1, colour="gray60") +
  geom_text(data=mynames, aes(long, lat, label = ISO_Ter1), size=4, fontface="bold") +
  
  scale_y_continuous(breaks = seq(mylimits$ymin, mylimits$ymax, 1),
                     labels = seq(mylimits$ymin, mylimits$ymax, 1) ) +
  scale_x_continuous(breaks = seq(mylimits$xmin, mylimits$xmax, 1) ) 

```


##### Page break 

### West-African area (FAO 34) 

```{r, echo=FALSE, fig.width=10, fig.asp=0.7, fig.align="center", message=FALSE, warning=FALSE}

# different options for specific areas to be shown
myareas   <- area34

# set limits based on selected areas
mylimits <- 
  filter(fao.df, F_CODE %in% myareas) %>% 
  summarise(xmin = floor(min(long, na.rm=TRUE)),
            xmax = ceiling(max(long, na.rm=TRUE)),
            ymin = floor(min(lat, na.rm=TRUE)),
            ymax = ceiling(max(lat, na.rm=TRUE)) )

# set area names for selected areas
mynames <-
  filter(fao.df, F_CODE %in% myareas) %>% 
  group_by(F_CODE) %>% 
  filter(row_number() == 1) %>% 
  select(F_CODE) %>% 
  left_join(fao_midpoints, by=c("F_CODE"))

# write.csv(fao.df, file="excel/fao.csv")
# sort(unique(fao.df$F_CODE))

fao.df %>%
  filter(F_CODE  %in% myareas) %>% 
  filter(hole == FALSE) %>% 
  # write.csv(., file="excel/fao.csv")
  
  ggplot() + 
  theme_publication() +
  theme(
    panel.grid.major   = element_line(colour="gray"),
    panel.grid.minor.y = element_line(colour="gray", linetype="dashed"),
    panel.spacing      = unit(c(0,0,0,0), "lines"),
    strip.background   = element_rect(colour=NA, fill = "#f0f0f0"),
    panel.border       = element_rect(colour="black" , size=0.2),
    legend.position    = "none") +
  
  labs(x = NULL, y = NULL) +    
  coord_quickmap(xlim=c(mylimits$xmin,mylimits$xmax) , ylim=c(mylimits$ymin,mylimits$ymax)) +

  geom_polygon(               aes(long, lat, group=group, fill=factor(F_DIVISION)),
                              size=0.1, colour="black", alpha=0.7) +
  geom_polygon(data=world.df, aes(long, lat, group=group), 
                              fill="cornsilk", size=0.1, colour="gray60") +
  geom_polygon(data=eez.df,   aes(long, lat, group=group), 
                              fill=NA, size=0.5, colour="gray40", alpha=0.7, lty="dashed") +
  geom_text(data=mynames, aes(long, lat, label = F_CODE), size=4, fontface="bold") +
  
  scale_y_continuous(breaks = seq(mylimits$ymin, mylimits$ymax, 1),
                     labels = seq(mylimits$ymin, mylimits$ymax, 1) ) +
  scale_x_continuous(breaks = seq(mylimits$xmin, mylimits$xmax, 1) ) 

```

## More information





```{r}
# generate files by country

load("../../prf/rdata/world.RData")
class(world)

map("spain")

library(readxl)
library(zoo)
bdy <- 
  read_excel(path="D:/XXX/GIS/WDB/afrika.xlsx", sheet="bdy") %>% 
  do(zoo::na.locf(.)) %>% 
  mutate(segment = gsub("(^segment )([0-9]{1,3})( .*$)","\\2",segment)) %>%
  mutate_at(c("lat","long"), funs(as.numeric)) %>% 
  # filter(!is.na(lat)) %>% 
  data.frame()

cil <- 
  read_excel(path="D:/XXX/GIS/WDB/afrika.xlsx", sheet="cil") %>% 
  do(zoo::na.locf(.)) %>% 
  mutate(segment = gsub("(^segment )([0-9]{1,3})( .*$)","\\2",segment)) %>%
  mutate_at(c("lat","long"), funs(as.numeric)) %>% 
  # filter(!is.na(lat)) %>% 
  data.frame()

cil %>%
  filter(segment == "1") %>% 
  ggplot() + 
  theme_publication() +
  theme(
    panel.grid.major   = element_line(colour="gray"),
    panel.grid.minor.y = element_line(colour="gray", linetype="dashed"),
    panel.spacing      = unit(c(0,0,0,0), "lines"),
    strip.background   = element_rect(colour=NA, fill = "#f0f0f0"),
    panel.border       = element_rect(colour="black" , size=0.2),
    legend.position    = "none") +
  
  labs(x = NULL, y = NULL) +    
  coord_quickmap(xlim=c(-30,0) , ylim=c(0,40)) +

  geom_point (aes(long, lat, group=segment, colour=factor(segment)),
                    size=0.1, alpha=0.7, guide=FALSE) +

  geom_point (data=bdy, aes(long, lat, group=segment, colour=factor(segment)),
                    size=0.1, alpha=0.7, guide=FALSE) 


```

